# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('falta', models.BooleanField()),
                ('trabaja', models.BooleanField()),
                ('positivos', models.PositiveIntegerField()),
                ('negativos', models.PositiveIntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.PositiveSmallIntegerField()),
                ('pasillo', models.CharField(max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('filas', models.PositiveIntegerField()),
                ('columnas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('1ESO', '1\xba ESO'), ('2ESO', '2\xba ESO'), ('3ESO', '3\xba ESO'), ('4ESO', '4\xba ESO'), ('1BACH', '1\xba BACH'), ('2BACH', '2\xba BACH'), ('1CFGM', '1\xba CFGM'), ('2CFGM', '2\xba CFGM'), ('1CFGS', '1\xba CFGS'), ('2CFGS', '2\xba CFGS')], max_length=20)),
                ('unidad', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.Profesor'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.Aula'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.Grupo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.Profesor'),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.Asignatura'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='asignaturas',
            field=models.ManyToManyField(to='instituto.Asignatura'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.Grupo'),
        ),
    ]
