# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-05 23:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotografias/')),
            ],
            options={
                'ordering': ['apellido1', 'apellido2', 'nombre'],
                'verbose_name_plural': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('falta', models.BooleanField(default=False)),
                ('trabaja', models.BooleanField(default=False)),
                ('positivos', models.PositiveIntegerField(blank=True, null=True)),
                ('negativos', models.PositiveIntegerField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.Alumno')),
            ],
            options={
                'ordering': ['asignatura', 'fecha', 'alumno'],
                'verbose_name_plural': 'anotaciones',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('distribucion', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['grupo', 'nombre', 'profesor'],
                'verbose_name_plural': 'asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.PositiveSmallIntegerField(choices=[(0, '1\xba ESO'), (1, '2\xba ESO'), (2, '3\xba ESO'), (3, '4\xba ESO'), (4, '1\xba BACH'), (5, '2\xba BACH'), (6, '1\xba CFGM'), (7, '2\xba CFGM'), (8, '1\xba CFGS'), (9, '2\xba CFGS'), (10, 'otros')])),
                ('unidad', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['curso', 'unidad'],
                'verbose_name_plural': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituto.Alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituto.Asignatura')),
            ],
            options={
                'ordering': ['asignatura', 'orden'],
                'verbose_name_plural': 'matriculas',
            },
        ),
        migrations.CreateModel(
            name='ProfesorUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'verbose_name_plural': 'profesores',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituto.ProfesorUser'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituto.Grupo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituto.ProfesorUser'),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.Asignatura'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='asignaturas',
            field=models.ManyToManyField(through='instituto.Matricula', to='instituto.Asignatura'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituto.Grupo'),
        ),
    ]
