# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='unidad',
            field=models.CharField(max_length=10),
        ),
    ]
