# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0003_auto_20161210_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instituto.Grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='curso',
            field=models.CharField(choices=[('1ESO', '1\xba ESO'), ('2ESO', '2\xba ESO'), ('3ESO', '3\xba ESO'), ('4ESO', '4\xba ESO'), ('1BACH', '1\xba BACH'), ('2BACH', '2\xba BACH'), ('1CFGM', '1\xba CFGM'), ('2CFGM', '2\xba CFGM'), ('1CFGS', '1\xba CFGS'), ('2CFGS', '2\xba CFGS')], max_length=20),
        ),
    ]
