# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0004_auto_20161210_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='negativos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anotacion',
            name='positivos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
