# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0005_auto_20161210_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellido1', 'apellido2'], 'verbose_name_plural': 'alumnos'},
        ),
        migrations.AlterModelOptions(
            name='anotacion',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'anotaciones'},
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['planta'], 'verbose_name_plural': 'aulas'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['curso'], 'verbose_name_plural': 'grupos'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['apellidos'], 'verbose_name_plural': 'profesores'},
        ),
    ]
