# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0006_auto_20161211_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name_plural': 'grupos'},
        ),
    ]
