# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0007_auto_20161211_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['curso'], 'verbose_name_plural': 'grupos'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotografias/'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instituto.Aula'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='grupo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='instituto.Grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='curso',
            field=models.PositiveSmallIntegerField(choices=[(0, '1\xba ESO'), (1, '2\xba ESO'), (2, '3\xba ESO'), (3, '4\xba ESO'), (4, '1\xba BACH'), (5, '2\xba BACH'), (6, '1\xba CFGM'), (7, '2\xba CFGM'), (8, '1\xba CFGS'), (9, '2\xba CFGS'), (10, 'otros')]),
        ),
    ]
