# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0008_auto_20170326_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias/'),
        ),
    ]
