# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0011_auto_20170326_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(default='fotografias/sinFoto.jpg', upload_to='fotografias/'),
        ),
    ]
