# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0013_auto_20170326_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituto.Grupo'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituto.Aula'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituto.Grupo'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituto.Profesor'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='pasillo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituto.Aula'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituto.Profesor'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='unidad',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
