# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0015_auto_20170326_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituto.Aula'),
        ),
    ]
